version: '3.9'

services:
  web:
    build: .
    image: austindocked/shopietbackend:revison1
    command: uvicorn backend.asgi:application --host 0.0.0.0 --port $PORT
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
